[package]
name = "vanguard-buy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alpaca-finance = "0.2.1"
clap = "2.33"
tokio = "0.2.25"
